name: EmailImagesObserver-Deploy

on: 
  # workflow_run:
  #     workflows: ["EmailImagesObserver-Image"]
  #     branches: [main]
  #     types: 
  #       - completed
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v4

      # Connect to Azure Kubernetes
      - name: Azure Kubernetes set context
        uses: Azure/aks-set-context@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
          resource-group: 'erabliereapi'
          cluster-name: 'kerabliereapi'

      # Deploy to kubernetes
      - name: Kubectl restart deployment
        run: |
          kubectl config current-context
          kubectl rollout restart deployment emailimagesobserver-deployment -n erabliereapi-prod
          kubectl rollout status deployment emailimagesobserver-deployment -n erabliereapi-prod